{-# OPTIONS --type-in-type #-}

module genSetoid2 where

open import Setoid
open import prop
open import Data.Empty
open import Data.Unit
open import Data.Product
open import Setoid.Fibra-SS
open import Setoid.Isomorphism

data IsoList : Setoid → Setoid → Set where
  empty : ∀ S → IsoList S S
  plus  : ∀ {Q R S} → Iso Q R → IsoList R S → IsoList Q S

append : ∀ {Q R S} → IsoList Q R → IsoList R S → IsoList Q S
append (empty _) l = l
append (plus φ l) m = plus φ (append l m)

flatten : ∀ {R S} → IsoList R S → Iso R S
flatten (empty S) = id-iso S
flatten (plus x p) = comp-iso (flatten p) x

reverse : ∀ {R S} → IsoList R S → IsoList S R
reverse (empty S) = empty S
reverse (plus x l) = append (reverse l) (plus (inv-iso x) (empty _))

mapIso* : ∀ {A B C D} → IsoList A B → IsoList C D → IsoList (ISO A C) (ISO B D)
mapIso* (empty S) (empty D) = empty _
mapIso* (empty S) (plus x m) = plus (Iso* (id-iso S) x) (mapIso* (empty S) m)
mapIso* (plus x l) (empty S) = plus (Iso* x (id-iso S)) (mapIso* l (empty S))
mapIso* (plus x l) (plus x₁ m) = plus (Iso* x x₁) (mapIso* l m)

postulate flatten-mapIso* : ∀ {A B C D} (l : IsoList A B) (m : IsoList C D) →
                          E (ISO (ISO A C) (ISO B D)) (flatten (mapIso* l m)) (Iso* (flatten l) (flatten m))
{- flatten-mapIso* (empty S) (empty D) x y = sym-p (iso-eq {S} {D} {x} {y})
flatten-mapIso* (empty S) (plus x m) x₁ y = {!!}
flatten-mapIso* (plus x l) m x₁ y = {!!} -}

record Graph : Set₁ where
  field
    Vertex : Set
    Edge   : Vertex → Vertex → Set

  data Path : Vertex → Vertex → Set where
    empty : ∀ x → Path x x
    single : ∀ {x} {y} → Edge x y → Path x y
    plus  : ∀ {x y z} → Edge x y → Path y z → Path x z
    minus : ∀ {x y z} → Edge y x → Path y z → Path x z

  record Fibra-GP : Set where
    field
      FibGP : Vertex → Set
      SubGP : ∀ {x y} → Edge x y → FibGP x ⇔ FibGP y

  open Fibra-GP public

  record Fibra-GS : Set where
    field
      FibGS : Vertex → Setoid
      SubGS : ∀ {x y} → Edge x y → IsoList (FibGS x) (FibGS y)

    SUBGS : ∀ {x y} → Path x y → IsoList (FibGS x) (FibGS y)
    SUBGS (empty x) = empty (FibGS x)
    SUBGS (single e) = SubGS e
    SUBGS (plus e p) = append (SubGS e) (SUBGS p)
    SUBGS (minus e p) = append (reverse (SubGS e)) (SUBGS p)

    record Section : Set where
      field
        app : ∀ x → El (FibGS x)
        wd  : ∀ x x' x* → app x ~< flatten (SubGS x*) > app x'

      postulate WD : ∀ x x' x* → app x ~< flatten (SUBGS x*) > app x'
{-      WD x .x (empty .x) = r (FibGS x) (app x)
      WD x x' (plus x₁ x*) = {!!}
      WD x x' (minus x₁ x*) = {!!} -}
  open Fibra-GS public

open Graph public

Setoid2Graph : Setoid → Graph
Setoid2Graph S = record { 
  Vertex = El S ;
  Edge = E S }
--TODO Define setoid generated by a graph.  Prove these are inverses.

Sigma-GP : ∀ G → Fibra-GP G → Graph
Sigma-GP G φ = record { 
  Vertex = Σ[ g ∈ Vertex G ] FibGP φ g ; 
  Edge = λ { (g , _) (g' , _) → Edge G g g' } }

data EdgeSig G (A : Fibra-GS G) : Σ[ g ∈ Vertex G ] El (FibGS A g) → Σ[ g ∈ Vertex G ] El (FibGS A g) → Set where
  horiz : ∀ {g g' a} (e : Edge G g g') → EdgeSig G A (g , a) (g' , transport (flatten (SubGS A e)) a)
  vert  : ∀ {g a a'} → E (FibGS A g) a a' → EdgeSig G A (g , a) (g , a')

π₁ : ∀ G A x y → EdgeSig G A x y → Path G (proj₁ x) (proj₁ y)
π₁ G A _ _ (horiz e) = single e
π₁ G A _ _ (vert x) = empty _

π₂ : ∀ G A x y (e : EdgeSig G A x y) → proj₂ x ~< flatten (SUBGS A (π₁ G A x y e)) > proj₂ y
π₂ G A _ _ (horiz e) = iso-transport (flatten (SubGS A e)) _
π₂ G A _ _ (vert x) = x

Sigma-GS : ∀ G → Fibra-GS G → Graph
Sigma-GS G A = record { 
  Vertex = Σ[ g ∈ Vertex G ] El (FibGS A g) ; 
  Edge = EdgeSig G A }

UnitG : Graph
UnitG = record { Vertex = ⊤ ; Edge = λ _ _ → ⊥ }

{- append : ∀ {X} {G : graphOver X} {x y z : X} → pathsIn G x y → pathsIn G y z → pathsIn G x z
append (empty x) q = q
append (plus e p) q = plus e (append p q)
append (minus e p) q = minus e (append p q)

append-reverse : ∀ {X} {G : graphOver X} {x y z : X}
                → pathsIn G y x → pathsIn G y z → pathsIn G z x
append-reverse p (empty _) = p
append-reverse p (plus e q) = append-reverse (minus e p) q
append-reverse p (minus e q) = append-reverse (plus e p) q 

conjugate : ∀ {X} {G : graphOver X} {x x' y y' : X}
            → pathsIn G x x' → pathsIn G y y' → pathsIn G x y → pathsIn G x' y'
conjugate {X} {G} x* y* p = append-reverse y* (append-reverse x* p)

reverse  : ∀ {X} {G : graphOver X} {x y : X} → pathsIn G x y → pathsIn G y x
reverse' : ∀ {X} {G : graphOver X} {x y : X} → pathsIn G x y → pathsIn G y x
reverse  {X} {G} {x} {y} p = append-reverse  (empty x) p
reverse' p = conjugate p (empty _) (empty _)

append  : ∀ {X} {G : graphOver X} {x y z : X} → pathsIn G x y → pathsIn G y z → pathsIn G x z
append' : ∀ {X} {G : graphOver X} {x y z : X} → pathsIn G x y → pathsIn G y z → pathsIn G x z
append  p q = append-reverse q (reverse p)
append' p q = conjugate (empty _) q p

generateS : ∀ {X : Set} → graphOver X → Setoid
generateS {X} G = record { El = X; E = pathsIn G; r = empty;
  E* = λ x* y* → (λ xy   → conjugate x* y* xy) ,
                 (λ x'y' → conjugate (reverse x*) (reverse y*) x'y') }

genFun : ∀ {X Y : Set} (f : X → Y) (G : graphOver X) (H : graphOver Y) → Set
genFun f G H = (e : Edg G) → pathsIn H (f (s G e)) (f (t G e))

{- genFuns : ∀ {X Y} (G : graphOver X) (H : graphOver Y) → graphOver (genFun {!!} {!!} {!!})
genFuns = {!!} -}

record genIso {X Y : Set} (fg : X ⇔ Y) (G : graphOver X) (H : graphOver Y) : Set where
  field
    I+ : genFun (proj₁ fg) G H
    I- : genFun (proj₂ fg) H G
    I= : ∀ (x : X) (y : Y) → pathsIn G x ((proj₂ fg) y) ⇔ pathsIn H ((proj₁ fg) x) y
open genIso

record genFibS {X : Set} (G : graphOver X) : Set where
  constructor fibra
  field
    Fam  : X → Set
    FamS : ∀ (x : X) → graphOver (Fam x)
    Fib  : ∀ (e : Edg G) → Fam (s G e) ⇔ Fam (t G e)
    FibI : ∀ (e : Edg G) → genIso (Fib e) (FamS (s G e)) (FamS (t G e))
open genFibS

Π-S-Base : ∀ {X : Set} (G : graphOver X) (F : genFibS G) → Set
Π-S-Base {X} G F = Σ[ f ∈ ((x : X) → Fam F x) ]
                    ((e : Edg G) →
                      pathsIn (FamS F (t G e)) (proj₁ (Fib F e) (f (s G e))) (f (t G e)))

{- Π-S-S : ∀ {X : Set} (G : graphOver X) (F : genFibS G) → graphOver (Π-S-Base G F)
Π-S-S G (fibra Fam FamS Fib FibI) =
  record {
   Edg = {!(e : Edg G X) → ?!};
   s = {!!};
   t = {!!} } -}

record Graph : Set₁ where
  field
    Vertex  : Set
    isGraph : graphOver Vertex
  open graphOver isGraph public

Fib-GS : Graph → Set
Fib-GS G = genFibS (Graph.isGraph G)

UnitG : Graph
UnitG = record { 
  Vertex = ⊤ ; 
  isGraph = record { 
    Edg = ⊤ ; 
    s = λ _ → tt ; 
    t = λ _ → tt } }

Sigma-GP : ∀ G → Fib-GS G → Graph
Sigma-GP G A = record { 
  Vertex = Σ[ g ∈ Graph.Vertex G ] genFibS.Fam A g ; 
  isGraph = record { 
    Edg = Σ[ e ∈ Graph.Edg G ] ({!!} ∋ {!!} ~[ {!!} ] {!!}) ; s = {!!} ; t = {!!} } }
-}
